{
 "title": "vaued",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Percentage of failed request",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(http_requests_total{status=~\"4..|5..\"}) / sum(http_requests_total)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of request per end point",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 13, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint, method) (http_requests_total)",
     "legendFormat": "{{endpoint}} {{status}} {{method}}"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_latency_seconds_count{endpoint=\"/books/\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "request_latency_seconds_count{endpoint=\"/books/<id>\"}",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "request_latency_seconds_count{endpoint=\"/books\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "status",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (http_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of request per day",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "rate(http_requests_total[1h])", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "rate(request_latency_seconds_count{endpoint=\"/books\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Methods Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (http_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UP time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 16 },
   "targets": [
    {
     "expr": "up{job=\"flask-api\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}