{
 "title": "vaued",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "UP time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()- process_start_time_seconds)/3600",
     "legendFormat": "hr"
    }
   ]
  },
  {
   "title": "Percentage of failed request",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(http_requests_total{status=~\"4..|5..\"}) / sum(http_requests_total)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UP period",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"flask-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "request latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 13, "y": 0 },
   "targets": [
    { "expr": "request_latency_seconds_sum", "legendFormat": "{{endpint}}{{method}}" },
    { "expr": "request_latency_seconds_count", "legendFormat": "{{endpoint}}{{method}}" }
   ]
  },
  {
   "title": "Request latency",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_latency_seconds_count{endpoint=\"/books/\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "request_latency_seconds_count{endpoint=\"/books/<id>\"}",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "request_latency_seconds_count{endpoint=\"/books\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (http_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of request per end point",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 13, "x": 7, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint, method) (http_requests_total)",
     "legendFormat": "{{endpoint}} {{status}} {{method}}"
    }
   ]
  },
  {
   "title": "HTTP Methods Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (http_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of request per day",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "rate(http_requests_total[1d])", "legendFormat": "{{label_name}}" }
   ]
  }
 ]
}